// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQH135YxxrIs2d99r6Wce1Q3xeT9TF2g',
    appId: '1:915211954713:web:1d90a30c15b8a4d6701888',
    messagingSenderId: '915211954713',
    projectId: 'ecommerceapp-c542a',
    authDomain: 'ecommerceapp-c542a.firebaseapp.com',
    storageBucket: 'ecommerceapp-c542a.firebasestorage.app',
    measurementId: 'G-8VD5YPP8V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxgNVsE2MI4lhJenf7sNsOwIAEoagXKg',
    appId: '1:915211954713:android:eac4030363146a77701888',
    messagingSenderId: '915211954713',
    projectId: 'ecommerceapp-c542a',
    storageBucket: 'ecommerceapp-c542a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3TUEj8Bgu0aEvg4aTx47bAimf8GybUU',
    appId: '1:915211954713:ios:3dac233fe30b008f701888',
    messagingSenderId: '915211954713',
    projectId: 'ecommerceapp-c542a',
    storageBucket: 'ecommerceapp-c542a.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3TUEj8Bgu0aEvg4aTx47bAimf8GybUU',
    appId: '1:915211954713:ios:3dac233fe30b008f701888',
    messagingSenderId: '915211954713',
    projectId: 'ecommerceapp-c542a',
    storageBucket: 'ecommerceapp-c542a.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQH135YxxrIs2d99r6Wce1Q3xeT9TF2g',
    appId: '1:915211954713:web:8b1977e6d0b713c1701888',
    messagingSenderId: '915211954713',
    projectId: 'ecommerceapp-c542a',
    authDomain: 'ecommerceapp-c542a.firebaseapp.com',
    storageBucket: 'ecommerceapp-c542a.firebasestorage.app',
    measurementId: 'G-8BZF747P8M',
  );
}
